Added points functionality.
patrycja93/OX pull request #8
Opened 2020-01-05 19:54 UTC by patrycja93

The Judge class displays players points and add points to players after each match.

2020-01-05 20:23 UTC, BulaMar requested changes
Each time you are doing better, but still some things are missing.

2020-01-05 20:23 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/ScoreBoard.java
> +    public void addWinnerPoints(Player player, int howMuch) {
Will points for wining match can differ or there also should be constant for those?

2020-01-05 20:23 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/gameflow/Match.java
> +        board.startMatch(numberOfMatch, activePlayer);
🤔  interesting, shouldn't match be started?

2020-01-05 20:23 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/gameflow/Mode.java
> +        Match match = Match.init(gameSettings.getBoardSize(), ui, spectatorsList);;
This can be back in for loop as it was.

2020-01-05 20:23 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/winnerchecker/Judge.java
> +    private static final int POINTS_FOR_WIN = 3;
Move it to score board.

2020-01-05 20:23 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/winnerchecker/JudgeStatements.java
> +        final int maxAmountOfPoints = getMaxAmountOfPoints(players);
maybe `getHighScore?`

2020-01-05 20:23 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/winnerchecker/JudgeStatements.java
> +        List<Player> losers = checkLosers(players, maxAmountOfPoints);
you do not need them when is draw, maybe it will be better to check it first?

2020-01-05 20:24 UTC, patrycja93 commented on src/main/java/pl/patrycja/ox/ScoreBoard.java
> +    public void addWinnerPoints(Player player, int howMuch) {
Ok I will correct it.

2020-01-06 01:43 UTC, patrycja93 commented
Little changes in classes according to your tips.

2020-01-06 09:13 UTC, BulaMar approved these changes
LGTM 👍  only minor things

2020-01-06 09:13 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/GameSettings.java
> +     * Return number of match
matches

2020-01-06 09:13 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/Observable.java
> +    void notifySpectators(int field, Player player);
missing documentation

2020-01-06 09:13 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/Observable.java
> +    void subscribe(Spectator spectator);
missing documentation

2020-01-06 09:13 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/gameflow/TicTacToe.java
> +        ModeFactory modeFactory = new ModeFactory(getLessThanFour(args), args);
Do you need both?

2020-01-06 09:13 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/ui/ConsoleUI.java
> +    public static final String ANSI_YELLOW = "\u001B[33m";
🥇

2020-01-06 09:13 UTC, BulaMar commented on src/main/java/pl/patrycja/ox/ui/ConsoleUI.java
> +            displayError("Unbroken number of sign cannot be greater then board size and less than 3. Values was changed.\n");
signs

2020-01-06 17:51 UTC, merged